name: Build and push docker image

on:
  push:
    branches:
      - 'main'

jobs:
  Build-And-Upload-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to dh
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create full image name
        run: |
          echo "IMAGE_NAME_AND_TAG=${MIXED_CASE_IMAGE_NAME,,}" >>${GITHUB_ENV}
        env:
          MIXED_CASE_IMAGE_NAME: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/rasa-model-server:${{ github.run_number }}
      - name: "Build and tag the docker image"
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME_AND_TAG }}
